version: "3"

services:

  solismqtt:
    build: ./src/solismqtt
#    depends_on:
#      - mosquitto
#      - homeassistant
    volumes:
      - '<your directory>/solismqtt-data/:/data'
      - '<your directory>/solismqtt-config/:/config'
      - '/etc/localtime:/etc/localtime:ro'
    logging:
        driver: "json-file"
        options:
            max-size: "50m"

